version: "3"

services:
  nginx:
    build: "./requirements/nginx/"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - inception

  mariadb:
    build: "./requirements/mariadb/"
    restart: always
    networks:
      - inception

  wordpress:
    build: "./requirements/wordpress/"
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

networks:
  inception:
    name: "inception"
